version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-remapac
    restart: always
    ports:
      - "${PORT_NGINX:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/${NGINX_CONF_FILE:-default.conf}:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      # - ./docker/nginx/certs:/etc/nginx/certs  # Monta la carpeta de certificados
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php
    networks:
      - appnetwork

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-remapac
    restart: always
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env
    ports:
      - "${PORT_PHP_MAPPING:-9000}:9000"
    networks:
      - appnetwork

  # redis:
  #   image: redis:latest
  #   container_name: redis-remapac
  #   restart: always
  #   ports:
  #     - "${PORT_REDIS:-6379}:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - appnetwork
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 3s
  #     timeout: s
  #     retries: 5

networks:
  appnetwork:
    external: true

# volumes:
#   redis_data:
