networks:
  appnetwork:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-remapac
    restart: always
    ports:
      - "${PORT_NGINX:-80}:80"
      - "${PORT_SSL:-443}:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/${NGINX_CONF_FILE:-default.conf}:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      # - ./docker/nginx/certs:/etc/nginx/certs  # Monta la carpeta de certificados
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php
    networks:
      - appnetwork

  mysql:
    image: mysql:8.0.16
    container_name: mysql-remapac
    restart: always
    tty: true
    ports:
      - "${PORT_MYSQL:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/remapac.sql:/docker-entrypoint-initdb.d/remapac.sql
    networks:
      - appnetwork
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis-remapac
    restart: always
    ports:
      - "${PORT_REDIS:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-remapac
    environment:
      PMA_HOST: mysql-remapac
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PORT_PHPMYADMIN:-81}:80"
    networks:
      - appnetwork
    depends_on:
      mysql:
        condition: service_healthy

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-remapac
    restart: always
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env
    ports:
      - "${PORT_PHP_MAPPING:-9000}:9000"
    networks:
      - appnetwork
    depends_on:
      mysql:
        condition: service_healthy

  # postfix-remapac:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: postfix-container-remapac
  #   restart: always
  #   ports:
  #     - "25:25"
  #   networks:
  #     - appnetwork
  #   depends_on:
  #     - php

volumes:
  mysql_data:
  redis_data:
